apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "myapp_v4.fullname" . }}-initdb
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "myapp_v4.fullname" . }}-initdb
    spec:
      restartPolicy: Never
      containers:
        - image: {{ .Values.image.userApi }}
          name: {{ include "myapp_v4.fullname" . }}-initdb-job
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp_v4.fullname" . }}-php-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp_v4.fullname" . }}-php-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp_v4.fullname" . }}-php-config
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp_v4.fullname" . }}-php-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp_v4.fullname" . }}-php-secret
                  key: DATABASE_PASSWORD
          command:
            - "php"
            - "./migrations/001_create_users_table.php"

  backoffLimit: 1
